### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jeyemwey** [kittyandrew/grafana-to-ntfy#12]
I'd like to add `grafana-to-ntfy` to the NixOS package repository [nixpkgs](https://github.com/NixOS/nixpkgs).

I kindly request you to add a suitable open-source license to the project. A well-defined license will not only ensure the legal use and distribution of the software but also facilitate its inclusion in various package management systems, including nixpkgs.

There a numerous resources such as [choosealicense.com](https://choosealicense.com) to help choosing a license, but the default is sadly `unfree`.

Thanks!

**Comment by weriomat** [comment]
Hey, 
it would be cool if you could add a license :) 
Thank you

**Comment by kittyandrew** [comment]
Thanks for the ping. Will add license out of my pure love for Nix, but fyi I've been extremely busy last few years and this project remained unmaintained. And the implementation itself is kinda bad, it should be just implemented in the grafana upstream or in some extension.

**Comment by jeyemwey** [comment]
Hi, thanks for considering a libre license for your software. I have created a PR to nixpkgs with the package. Hope it's useful to you, too: https://github.com/NixOS/nixpkgs/pull/346731
