### ISSUE TITLE
Setting up fails

### ISSUE THREAD

**Issue by Dima-Kal** [kittyandrew/grafana-to-ntfy#3]
When sending test during the ntfy configuration, the following error is shown in container:   

>> `Json < data :: Notification >` data guard failed: Parse("{\"receiver\":\"\",\"status\":\"firing\",\"alerts\":[{\"status\":\"firing\",\"labels\":{\"alertname\":\"TestAlert\",\"instance\":\"Grafana\"},\"annotations\":{\"dashboard_id\":\"111\",\"description\":\"asdasd\",\"summary\":\"Notification test\"},\"startsAt\":\"2022-10-25T22:09:02.374605697+03:00\",\"endsAt\":\"0001-01-01T00:00:00Z\",\"generatorURL\":\"\",\"fingerprint\":\"57c6d9296de2ad39\",\"silenceURL\":\"https://grafana.domain.com/alerting/silence/new?alertmanager=grafana\\u0026matcher=alertname%3DTestAlert\\u0026matcher=instance%3DGrafana\",\"dashboardURL\":\"https://grafana.domain.com/d/123\",\"panelURL\":\"\",\"valueString\":\"[ metric='foo' labels={instance=bar} value=10 ]\"}],\"groupLabels\":{},\"commonLabels\":{\"alertname\":\"TestAlert\",\"instance\":\"Grafana\"},\"commonAnnotations\":{\"dashboard_id\":\"111\",\"description\":\"asdasd\",\"summary\":\"Notification test\"},\"externalURL\":\"https://grafana.domain.com/\",\"version\":\"1\",\"groupKey\":\"{alertname=\\\"TestAlert\\\", instance=\\\"Grafana\\\"}2022-10-25 22:09:02.374605697 +0300 IDT m=+76325.319301984\",\"truncatedAlerts\":0,\"orgId\":1,\"title\":\"[FIRING:1]  (TestAlert Grafana)\",\"state\":\"alerting\",\"message\":\"**Firing**\\n\\nValue: [ metric='foo' labels={instance=bar} value=10 ]\\nLabels:\\n - alertname = TestAlert\\n - instance = Grafana\\nAnnotations:\\n - dashboard_id = 111\\n - description = asdasd\\n - summary = Notification test\\nSilence: https://grafana.domain.com/alerting/silence/new?alertmanager=grafana\\u0026matcher=alertname%3DTestAlert\\u0026matcher=instance%3DGrafana\\nDashboard: https://grafana.domain.com/d/123\\n\"}", Error("missing field `dashboard_id`", line: 1, column: 1525)).
   >> No 422 catcher registered. Using Rocket default.

setup is default values as shown in the example

**Comment by Y0ngg4n** [comment]
@Dima-Kal same issue here

**Comment by DoTheEvo** [comment]
same here

**Comment by kittyandrew** [comment]
>  I guess it did not update for grafana v9
You were indeed correct, my grafana is v8, and the scheme of notification payload has changed.
Should be fixed in the latest version of the container, although I myself do not use v9, so I didn't test it. If you do decide to test it, please let me know how that went.

**Comment by DoTheEvo** [comment]
yeap, works

![pic_of_it](https://i.imgur.com/PsQfNiz.jpg)
