### ISSUE TITLE
Specify priority

### ISSUE THREAD

**Issue by doits** [kittyandrew/grafana-to-ntfy#9]
Just sent my first test messages successfully, thanks for this project!

One thing I'm missing already: I'd want to specify for an alert if it has a high priority (--> waking me up at night) or not (--> I can handle it next working day). I can set custom notification settings for different priorities ntfy, so this would be a nice feature to use.

Could there be a way to specify the priority of the notification? I could imagine to add a label named `priority` for an alert, so `grafana-to-ntfy` could check this label? It probably should loop over the `alerts` array and check the labels of each alert to use the highest one provided?

Or is there another/better way? WDYT?

**Comment by doits** [comment]
For reference here's the implementation detail in ntfy: https://docs.ntfy.sh/publish/#message-priority

**Comment by kittyandrew** [comment]
Added this through tags/labels (tested only on my grafana 7 though and latest grafana docker image).
https://github.com/kittyandrew/grafana-to-ntfy?tab=readme-ov-file#priority-support
